export const VALID_CATEGORIES_BY_SOFTWARE: Record<string, string[]> = {
  TMS: [
    'LOGIN', 'ENROLLMENT', 'ASSESSMENT', 'CERTIFICATION', 'COURSE_DATA',
    'BATCH_DATA', 'TRAINEE_DATA', 'CLAIM_1_BILLING', 'CLAIM_2_BILLING',
    'CLAIM_3_BILLING', 'OTHER',
  ],
  FINMAN: [
    'LOGIN', 'LEDGER', 'BUDGET', 'SOE', 'DOUBLE_COLUMN_CASHBOOK', 'OTHER',
  ],
};